name: deploy_to_aws_lambda_function
on:
  push:
    branches:
    - main

jobs:
  deploy_to_lambda:
    name: deploy_to_lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: listing files in repository
        run: ls -l
      - name: zip the code
        run: zip -r python.zip lambda_function.py
      - name: listing files in repository
        run: ls -l
      - name: aws cli version
        run: aws --version
